version: '3.4'

services:
  blog:
    image: ${DOCKER_REGISTRY-}blog
    build:
      context: .
      dockerfile: Blog/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver  
    environment:
      ConnectionStrings_DefaultConnection: "Server=sqlserver;Database=DotnetBlog;User Id=sa;Password=Free@Palestine321;Encrypt=False;"
      AuthMessageSenderOptions_SendGridKey: "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" 
      AuthMessageSenderOptions_SendGridDomain: "salmanpatrick5@gmail.com" 
      CLOUDINARY_URL: "cloudinary://539697798452188:1rQV_o8Fui_rz8hGhE1AOuMOrpE@di6cw5ehp"
      ASPNETCORE_ENVIRONMENT : "Production"
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "Free@Palestine321" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"   # Expose SQL Server port
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data: